//Making the refresh animation
const tl = gsap.timeline({ defaults: { ease: "power1.out" } });

tl.to(".text", { y: "0%", duration: 1, stagger: 0.25 });
tl.to(".slider", { y: "-100%", duration: 1.5, delay: 0.5 });
tl.to(".intro", { y: "-100%", duration: 1 }, "-=1");
//Wie schnell der text eingeflogen kommt
//tl.fromTo(".main", { opacity: 0 }, { opacity: 1, duration: 1 });
//tl.fromTo(".btn", { opacity: 0 }, { opacity: 1, duration: 1 }, "-=1");

//starting with acutal page
let eo = [
    "Barfuß oder Socken?",
    "Unsichtbar sein oder Gedanken lesen?",
    "Unterwasser atmen oder Fliegen können?",
    "Jogginghose oder Jeans?",
    "Samstag oder Sonntag?",
    "Schwitzen oder Frieren?",
    "Android oder iPhone?",
    "Stadt oder Dorf?",
    "McDonald's oder Burger King?",
    "Pizza oder Nudeln?",
    "Schokolade oder Chips?",
    "Aufzug oder Treppe?",
    "Hund oder Katze?",
    "Sommer oder Winter?",
    "Herbst oder Frühling?",
    "Cola oder Pepsi?",
    "Reisen oder Balkonien?",
    "Strandurlaub oder Städtetrip?",
    "Viel Geld oder viel Freizeit?",
    "Reich oder berühmt?",
    "Geburtstag oder Weihnachten?",
    "Frühstück oder Abendessen?",
    "Star Wars oder Star Trek?",
    "Harry Potter oder Herr der Ringe?",
    "Marvel oder DC?",
    "Bösewicht oder Superheld?",
    "Süßes oder salziges Popcorn?",
    "Horror oder Comedy?",
    "Kino oder Netflix?",
    "Rache oder Vergebung?",
    "Optimist oder Pessimist?",
    "Realist oder Träumer?",
    "Tattoo oder Piercing?",
    "In einer WG oder alleine leben?",
    "Nachricht schreiben oder anrufen? ",
    "Liebe oder Geld? ",
    "Perfekte Haare oder perfekte Zähne? ",
    "Vintage Style oder neu? ",
    "Neues Handy oder neuer Laptop? ",
    "Jetzt jünger oder älter sein",
    "Intelligenz oder Humor?",
    "Film oder Serie?",
    "Im Lotto gewinnen oder den/die Seelenverwandte/n finden",
    "Nach Schweiß riechen oder aus dem Mund stinken?",
    "Lieber 100 km/h rennen können, oder 1 km/h fliegen?",
    "Gegen ein entengroßes Nashorn kämpfen müssen oder gegen 10 nashorngroße Enten?",
    "Wärst du lieber ein ehrliches Arschloch, oder ein netter Lügner?",
    "Alles wissen oder alles haben?",
    "Eine*n Psychopath*in daten oder ein* Psychopath*in sein?",
    "Wissen WANN du stirbst oder wissen, WIE du stirbst?",
    "Vergessen, wer du bist, oder vergessen wer deine Freund*innen sind?",
    "Als du selbst wiedergeboren werden oder nach dem Zufallsprinzip als ein Tier wiedergeboren werden?",
    "Besseres Gesundheitssystem oder besseres Bildungssystem?",
    "Entweder allein verschollen in einem Gebirge oder gestrandet auf einer einsamen Insel?",
    "Lieber extrem schlau oder ein extremer Glückspilz?",
    "Ewig auf der Flucht oder 10 Jahre im Gefängnis?",
    "Jetzt eine Millionen Euro bekommen oder in 10 Jahren 50 Bitcoin?",
    "Eine 99% Chance, 1 Millionen zu gewinnen – oder eine 50/50 Chance, eine Milliarde zu gewinnen?",
    "Der schlaueste oder der reichste Mensch der Welt sein?",
    "100 Fremde retten oder einen geliebten Menschen retten?",
    "Die Zukunft kennen oder in die Vergangenheit reisen?",
    "Große Schmerzen für 10 Minuten oder unterschwellige Schmerzen für 24 Stunden?",
    "Freiheit oder Hoffnung? ",
    "Plötzlicher Erfolg oder geplanter Erfolg?",
    "Alte Freundschaft wiederbeleben oder alte Liebe wiederbeleben?",
    "Im Lotto gewinnen oder den Traumjob finden?",
    "Verärgerte Eltern oder verärgerte Freunde?",
    "Fragen stellen oder Fragen beantworten?",
    "Keine Gäste auf deiner Beerdigung oder keine Gäste auf deiner Hochzeit? ",
    "In der Friendzone landen oder geghosted werden?",
    "Würdest du eher die Helligkeit oder die Lautstärke auf deinem Handy für immer niedrig einstellen?", 
    "Würdest du eher die Katze deiner Familie oder eine streunende Katze sein?", 
    "Würdest du eher die Unterseite deines Schuhs lecken oder den großen Zeh eines Fremden lecken?", 
    "Würdest du eher Dinge sehen, die sehr weit entfernt sind (wie mit einem Fernglas), oder Dinge aus der Nähe sehen (wie mit einem Mikroskop)?", 
    "Würdest du eher ein berühmter Schauspieler/eine berühmte Schauspielerin oder ein berühmte Sänger/eine berühmte Sängerin sein?", 
    "Würdest du eher ein Doppel-Date mit deinen Eltern oder mit den Eltern deines Partners haben?", 
    "Würdest du eher ein lebenslanges Gratis-Abo für Netflix oder eine unbegrenzte Geschenkkarte für Starbucks haben?", "Würdest du eher ein magisches Fahrrad haben, das fliegen kann, oder einen Roboter besitzen?",
    "Würdest du eher ein peinliches, betrunkenes Bild von dir als Instagram-Story posten, die dein Schwarm sieht, oder deinem Schwarm eine peinliche Direktnachricht schicken?", 
    "Würdest du eher eine elefantengroße Katze oder einen katzengroßen Elefanten haben?", 
    "Würdest du eher eine ganze Zwiebel oder eine ganze Zitrone essen?", 
    "Würdest du eher eine Woche lang die internationale Raumstation besuchen oder eine Woche in einem Unterwasserhotel leben?", "Würdest du eher einen Drachen oder ein Einhorn als Haustier haben?", 
    "Würdest du eher einen fliegenden Teppich oder ein durchsichtiges U-Boot haben?", 
    "Würdest du eher einen Kopf, so groß wie ein Tennisballs oder einen Kopf so groß wie eine Wassermelone haben?", "Würdest du eher einen Schwanz wie einen Hund oder Flügel haben, die nicht fliegen können?", 
    "Würdest du eher einen zusätzlichen Finger oder eine zusätzlichen Zehe haben?", 
    "Würdest du eher einmal pro Woche deine kleine Zehe anstoßen oder einen Daumen verlieren?", 
    "Würdest du eher extreme Akne haben, die nur an Stellen auftritt, die mit Kleidung bedeckt sind, oder mittelschwere Akne, die nur auf deinem Gesicht auftritt?", 
    "Würdest du eher fliegen oder unsichtbar sein können?", 
    "Würdest du eher für den Rest deines Lebens lieber jeden Tag kalt duschen oder für nur kaltes Essen essen?", "Würdest du eher Gedanken lesen oder in die Zukunft sehen können?", 
    "Würdest du eher Grashaare oder eine Gurkennase haben?", 
    "Würdest du eher Gummibären niesen oder Schokolade weinen?", 
    "Würdest du eher im Game of Thrones Universum oder im The Walking Dead Universum leben?", 
    "Würdest du eher immer overdressed oder immer underdressed sein?", 
    "Würdest du eher immer T-Shirts tragen, die eine Größe zu klein oder zwei Größen zu groß sind?", 
    "Würdest du eher in deinem Haus nur eine einzige Farbe haben oder jede einzelne Wand und Tür mit einer andere Farbe anstreichen?", "Würdest du eher in den Wolken oder unter Wasser leben?", 
    "Würdest du eher in der Schule oder auf einer Familienfeier nur in Unterwäsche aufwachen?", 
    "Würdest du eher in einem Obdachlosenheim mit kostenlosem WLAN leben oder in einer wunderschönen Villa, das von jeglichem Kontakt von der Außenwelt isoliert ist?", 
    "Würdest du eher in einem Schloss oder in einem Raumschiff leben?", 
    "Würdest du eher in Pudding oder in Nutella schwimmen?",
    "Würdest du eher jede Mahlzeit wie einen Smoothie trinken oder nie wieder Schokolade essen?", 
    "Würdest du eher jeden Tag dein Lieblingsessen essen oder jeden Morgen 5 Euro unter deinem Kissen finden?",
    "Sex mit Megan Fox mit einem Penis oder Jason Momoa mit einer Vagina haben?", 
    "24h am Tag geil seien oder nur einmal pro Jahr?", 
    "an ein Bett gefesselt und vergessen werden oder ein Sexspielzeug in dir verlieren?", 
    "Anal gefingert oder vaginal gefistet werden wollen?", 
    "Anal- oder Oralsex haben?", 
    "Analsex haben oder keinen Analsex haben?", 
    "bei einem Gangbang oder einem Dreier mitmachen?", 
    "beim Betrügen erwischt werden oder deinen Partner beim Betrügen erwischen?", 
    "beim ersten Date Sex haben oder mit dem Sex einen Monat lang warten?", 
    "beim Sex deinen Knöchel verstauchen oder den Penis deines Partners brechen?", 
    "beim Sex furzen oder beim Küssen rülpsen?", 
    "beim Sex gewürgt oder geschlagen werden?", 
    "beim Sex seltsam stöhnen oder jedes Mal ein hässliches Gesicht machen, wenn du kommst?", 
    "betrunken oder bekifft Sex haben?", 
    "bevorzugen, dass dein Partner während des Vorspiels nur seine Hände benutzt oder nur seinen Mund?", 
    "Brüste oder Ärsche bevorzugen?", 
    "das Küssen oder den Sex für immer aufgeben?", 
    "dein Date in einer Bar unauffällig mit der Hand befriedigen oder auf einem Parkplatz oral befriedigen?", 
    "deine Eltern beim Sex erwischen oder von deinen Eltern beim Sex erwischt werden?", 
    "deine Rückenhaare waxen lassen oder deine Sackhaare?", 
    "deinem Chef eine schmutzige Nachricht senden oder deiner Mutter eine sexy Sprachnachricht hinterlassen?", 
    "deinem Chef eine schmutzige Textnachricht senden oder deiner Mutter eine sexy Sprachnachricht hinterlassen?", 
    "deinem Partner zusehen, wie er mit einer anderen Person Sex hat oder würdest du deinen Partner zusehen lassen, wie du mit einer anderen Person Sex hast?", 
    "deinen Intimbereich piercen oder tätowieren lassen?",
    "deinen Partner beim Masturbieren beobachten oder dich von deinem Partner beim Masturbieren beobachten lassen?", 
    "deinen Partner beim Sex dominieren oder dich von deinem Partner beim Sex dominieren lassen?", "deinen Partner betrügen oder einen Dreier vorschlagen?", 
    "deinen Partner mit deinem besten Freund (Freundin) oder mit dem besten Freund (Freundin) deines Partners schlafen lassen?", 
    "den Arsch deines Partners lecken oder deinen Arsch von deinem Partner lecken lassen?", "den ganzen Tag masturbieren oder den ganzen Tag Sex haben?", 
    "der dominante oder submissive Sexpartner sein?", 
    "der große oder kleine Löffel sein?", 
    "drei Brüste oder einen Busen von der Größe einer Wassermelone haben?", 
    "ein Cam Girl/Boy sein oder ein Sexvideo von dir veröffentlichen?", "ein Dessous mit Spitze oder ein Bondage Outfit aus Latex bevorzugen?", 
    "ein erstes Date mit einem leidenschaftlichen Kuss oder mit Sex beenden?", 
    "ein extrem gutes Vorspiel, aber miesen Sex oder ein mieses Vorspiel, aber großartigen Sex haben?", "ein Jahr lang einen Keuschheitsgürtel tragen oder ein Jahr lang jemandes Sexsklave/ Sexsklavin sein?", 
    "ein Jahr lang einen Keuschheitsgürtel tragen oder ein Jahr lang von jemanden ein Sexsklave sein?", "ein Monat auf Pornos verzichten oder ein Monat auf Sex verzichten?", 
    "ein schlechtes Vorspiel und guten Sex haben wollen,, oder ein gutes Vorspiel und schlechten Sex?", "ein Sugar Daddy/eine Sugar Mommy sein oder einen Sugar Daddy/eine Sugar Mommy haben?", "eine erotische Massage bekommen oder von deinem Partner bekocht werden?", 
    "eine Peitsche beim Sex verwenden oder in einem Livestream Sex haben?", 
    "eine Prostatamassage erhalten (oder geben) oder dein Arschloch geleckt bekommen?",
    "eine Sexpuppe benutzen oder ein Fleshlight?", 
    "einen Analplug oder Liebeskugeln verwenden?", 
    "einen beschnittenen oder unbeschnittenen Penis bevorzugen?",
    "einen Blowjob während einer Autofahrt oder in einem Restaurant bekommen?", 
    "einen Dreier mit deinem Ex oder mit dem Ex deines Partners haben?", 
    "einen Dreier mit einer Person, die du kennst, oder einem Fremden haben?",
    "einen Dreier mit Personen, die du kennst oder mit fremden Personen haben?",
    "einen Dreier mit zwei Frauen oder zwei Männern haben?", 
    "einen Dreier oder eine Gangbang haben?", 
    "einen erotischen Roman lesen oder erotischen Film anschauen?", 
    "einen erotischen Roman lesen oder Pornos schauen?", 
    "einen Finger im Po haben oder jemanden anderen einen Finger in den Po stecken?", 
    "einen Handjob oder Blowjob geben / erhalten?", 
    "einen Klaps auf den Hintern bevorzugen oder von jemanden während dem Sex leicht gewürgt zu werden?", 
    "einen kleinen dicken Penis haben oder einen langen dünnen Penis?", 
    "einen kleinen Penis haben, der ejakulieren kann, oder einen großen Penis, der nicht ejakulieren kann?", 
    "einen Knutschfleck haben oder jemanden einen Knutschfleck geben?", 
    "einen Lapdance geben oder bekommen?", 
    "einen Lapdance geben oder erhalten?", 
    "einen Mann oder eine Frau in einem Porno ansehen um dich selbst geil zu machen?", 
    "einen Partner haben, der in 60 Sekunden kommt, oder einen Partner, der in 3 Stunden kommt?", "einen Partner haben, der keinen Oralsex mag, oder einen Partner, der von Analsex besessen ist?", 
    "einen Partner mit einer Sexsucht oder einen Partner mit einem geringen Sexualtrieb haben?", "einen Partner oder mehrere Partner haben?", 
    "einen Porno mit deinem Partner gemeinsam anschauen oder eine Szene aus einem Porno mit deinem Partner nachstellen?", 
    "einen sehr attraktiven Ehepartner haben, der nur einmal im Monat Sex mit dir hat, oder einen hässlichen Ehepartner, der jeden Tag Sex mit dir hat?", 
    "einen Sexfilm auf einer Online-Plattform veröffentlichen, bei dem man dein Gesicht sieht, oder würdest du ein privates Sexvideo auf einer Party abspielen, bei dem man dein Gesicht nicht sieht?", 
    "Femdom oder Maledom bevorzugen?", 
    "Fisting oder Doppelpenetration ausprobieren?", 
    "furzen, während du geleckt wirst oder rülpsen, während du rumschmust?", 
    "für den Rest deines Lebens jeden Tag geil sein oder nur einmal im Jahr geil sein?",
    "für den Rest deines Lebens nur mit einer Person oder mit mehreren Personen zusammensein?", "für den Rest deines Lebens nur noch Periodensex oder Analsex haben?", 
    "für den Rest deines Lebens nur noch Sex in der Missionarsstellung oder in Doggy-Style haben?", "für den Rest deines Lebens regelmäßig mittelmäßigen Sex haben oder unglaublich guten Sex nur einmal im Jahr haben?", 
    "für den Rest deines Lebens schlechten Sex haben oder nie wieder Sex haben?",
    "für den Rest deines Lebens zehnmal am Tag Sex haben oder für ein Jahr keinen Sex haben?", "für einen Monat aufgeben Sex zu haben oder zu masturbieren?", 
    "für einen Monat keinen Alkohol trinken oder für einen Monat nicht masturbieren?", 
    "für immer Sex im Dunklen haben oder für immer Sex in der Öffentlichkeit haben?", 
    "für Sex bezahlen oder für Sex bezahlt werden?", 
    "gefistet werden oder jemand anderen fisten?", 
    "gemeinsam mit deinem Partner oder alleine masturbieren?", 
    "getragene Höschen im Internet verkaufen oder bei einer Sex-Hotline arbeiten?", 
    "heimlich Sex mit deinem Cousin haben oder keinen Sex mit deinem Cousin, aber jeder würde denken, dass du es getan hast?", 
    "herausfinden wollen, dass dein letzter Sexualpartner/deine letzte Sexualpartnerin verwandt mit dir war, oder herausfinden, dass die letzte Person, mit der du geschlafen hast, ein Serienmörder war?", 
    "herausfinden wollen, dass dein Partner mit deinen Eltern oder mit deinem besten Freund geschlafen hat?", 
    "immer für 6 Stunden Sex haben oder nie wieder Sex haben?",
    "immer oben oder immer unten sein?", 
    "in der Badewanne oder der Dusche Sex haben?", 
    "in der Öffentlichkeit Sex haben oder nackt rumlaufen?", 
    "in einem Dessous oder einem Umschnalldildo in der Öffentlichkeit herumlaufen?", 
    "jeden Tag mit deinem Partner kuscheln oder jeden Tag mit deinem Partner gemeinsam duschen?", "jedes Mal \"Ich liebe Jesus\" rufen, wenn du kommst, oder \"Ich habe eine Geschlechtskrankheit\"?", 
    "jedes Mal eine Benachrichtigung erhalten, wenn deine Eltern Sex haben, oder möchtest du, dass dein Büro jedes Mal benachrichtigt wird, wenn du Sex hast?", 
    "jedes Mal zum Orgasmus kommen, wenn du niest oder wenn du gähnst?", "jemandem beim Sex zuschauen oder von jemand anderen beim Sex beobachtet werden?", "jemandem einen Deepthroat-Blowjob geben oder Analsex haben?", 
    "jemanden beim Sex fesseln oder gefesselt werden?",
    "jemanden daten, der auf BDSM steht oder auf Blümchensex?",
    "jemanden daten, der auf BDSM steht oder der auf langweiligen Blümchensex steht?", "jemanden daten, der ein schlechter Küsser ist oder schlecht im Bett ist?",
    "jemanden daten, der fünf Sekunden zum Kommen braucht oder jemanden, der fünf Stunden zum Kommen braucht?",
    "jemanden einen Deepthroat Blowjob geben oder jemanden Anal fisten?", 
    "jemanden oral befriedigen oder oral befriedigt werden?",
    "jemanden während dem Sex würgen oder gewürgt werden?", "jetzt sofort schwanger werden oder niemals schwanger werden?",
    "kleine oder große Brüste bevorzugen?",
    "kleine oder große Schamlippen bevorzugen?", 
    "kuscheln oder rummachen?", 
    "mit deinem besten Freund / deiner besten Freundin rummachen oder mir beim Rummachen mit deinem besten Freund / deiner besten Freundin zusehen?", 
    "mit deinem besten Freund / Freundin Sex haben oder mit meinem besten Freund / Freundin?", 
    "mit deinem Ex oder mit einem Promi schlafen, den du hasst?", 
    "mit einem Blowjob am Morgen überrascht werden oder einen Blowjob vor dem Schlafen gehen bekommen?", 
    "mit einem Sugar Daddy oder einer Sugar Mommy schlafen oder in einem Porno mitspielen?", "mit jemandem ausgehen, der schlecht küsst oder schlecht im Bett ist?",
    "mit jemandem ausgehen, der sich weigert zu kuscheln, oder mit jemandem, der sich weigert, dich oral zu befriedigen?", 
    "mit jemanden schlafen, der 10 Jahre älter ist als du oder mit jemanden, der 10 Jahre jünger ist als du?", "mit jemanden Sex haben, der währenddessen die ganze Zeit spricht, oder jemanden, der keinen Ton von sich gibt?", 
    "mit jemanden zusammen sein, der miserable im Bett ist aber dich zum Lachen bringt oder mit jemanden, der großartig im Bett, aber unglaublich langweilig ist?", 
    "mit oder ohne einem Sexspielzeug masturbieren?", 
    "mit oder ohne Licht Sex haben?", 
    "mit oder ohne Porno masturbieren?",
    "morgens den \"Walk of Shame\" gehen oder dein One-Night-Stand aus deiner Wohnung rausschmeißen?", "morgens oder abends Sex haben?", 
    "nie mehr Sex haben oder nie mehr das Internet benutzen?", 
    "nie wieder einen Orgasmus haben oder wissen, dass dein Partner noch nie einen Orgasmus bei dir hatte?", "nie wieder mastubieren oder nie wieder Sex haben?",
    "nie wieder masturbieren oder nie wieder feste Nahrung essen?",
    "nie wieder Sex haben oder Bing für den Rest deines Lebens als Suchmaschine benutzen?", "nie wieder Sex haben oder nie wieder masturbieren?", 
    "nur deine Hände für das Vorspiel verwenden oder nur deinen Mund?",
    "nur Sex haben, während du einen Horrorfilm anschaust, oder nur wenn du \"Dora The Explorer\" anschaust?",
    "nur Sex im Schlafzimmer haben oder nur Sex außerhalb des Schlafzimmers?",
    "nur zu Pornos masturbieren, welche nicht länger als 6 Sekunden dauern, oder nur zu Pornoparodien wie Star Wars und Pokémon masturbieren?", 
    "oral befriedigt werden während du deinen Lieblingsfilm anschaust oder jemand anderen oral befriedigen?",
    "Pegging oder Fisten bevorzugen?", 
    "Rollenspiele oder BDSM ausprobieren?",
    "romantische Dinge im Bett machen oder versaute Sachen ausprobieren?", "schlecht küssen oder schlecht im Oralsex sein?", 
    "schlucken oder spucken?", "sechs Stunden am Tag mit einer Erektion herumlaufen oder nie wieder eine Erektion haben?", "Sex am Morgen oder Abend haben?", 
    "Sex im Auto deiner Eltern haben oder auf der Rückbank eines Taxis?",
    "Sex im Bett deiner Eltern haben oder in deinem Kinderzimmer während deine Eltern zuhause sind?", 
    "Sex im Schlafzimmer deiner Eltern haben oder Sex in deinem Kinderzimmer, während deine Eltern zu Hause sind?", 
    "Sex in der Missionarsstellung oder Doggy Style haben?",
    "Sex in einem schmutzigen Hotelbett oder in einer stinkenden öffentlichen Toilette haben?", "Sex mit deinem besten Freund oder deinem/deiner Ex haben?", 
    "Sex mit der Mutter oder dem Vater deines besten Freundes haben?",
    "Sex mit der Person zu deiner Linken oder zu deiner Rechten haben?", 
    "Sex mit einem \"Beißer\" oder einem \"Schreihals\" haben?", 
    "Sex mit jemandem haben, der die ganze Zeit spricht, oder mit jemandem, der keinen Ton von sich gibt?",
    "Sex mit jemandem haben, der einen russischen oder indischen Akzent hat?", "Sex mit jemandem haben, der einen schönen Körper, aber ein hässliches Gesicht hat, oder mit jemandem, der einen hässlichen Körper hat, aber ein schönes Gesicht?",
    "Sex mit jemandem haben, der niemals duscht oder der niemals seine Zähne putzt?",
    "Sex mit jemandem haben, der sehr attraktiv, aber schlecht im Bett ist, oder mit jemandem, der hässlich, aber unglaublich gut im Bett ist?",
    "Sex mit jemandem haben, der sich weigert, die Socken auszuziehen, oder mit jemandem, der ein komisches Orgasmusgesicht hat?",
    "Sex mit Kondom oder Sex ohne Kondom haben?",
    "Sex mit Licht an oder Licht aus haben?",
    "Sex mit meinem besten Freund oder mit deinem besten Freund haben?", "Sex mit mit Gleitgel oder ohne haben?",
    "Sex mit oder ohne Kondom haben?", 
    "Sex mit Schuhen oder Sex mit Socken haben?",
    "Sex mit verbundenen Augen oder mit Handschellen haben?", "Sex von hinten oder von vorne haben?",
    "Sex vor Fremden haben oder Sex vor dieser Gruppe haben?", "sexten oder Telefonsex haben?",
    "siebzehn Hoden oder einen Hoden von der Größe einer Kokosnuss haben?", "Sperma in die Haare oder in die Augen bekommen?",
    "Sperma schlucken, das nach Pisse schmeckt, oder von deinem Partner angepinkelt werden?",
    "tot auf einem Haufen Sexspielzeuge oder einem Haufen Drogen aufgefunden werden?", 
    "unten oder oben sein?", 
    "unter dem Tisch eines Restaurants oder unter dem Tisch im Haus deiner Eltern gefingert werden?",
        "versauten Sex oder Blümchensex haben?", 
    "versauten Sex oder romantischen Sex haben?", "von unten oder oben Sex haben?",
    "vor dem Spiegel masturbieren oder Sex haben?", "wollen, dass dein Partner/deine Partnerin immer zu lachen oder zu weinen beginnt, wenn er/sie dich nackt sieht?",
    "während dem Sex Dirty Talk betreiben oder während dem Sex nichts reden?",
    "während dem Sex erwischt werden oder beim Küssen einer Sexpuppe?", "zum Masturbieren eine elektrische Zahnbürste oder einen Duschkopf verwenden?",
    "zärtlichen Sex für eine Stunde haben oder harten Sex für 10 Minuten?"

    ]
let textEl1 = document.getElementById("text1").innerHTML = get_random(eo)

function get_random (list) {
    return list[Math.floor((Math.random()*list.length))];
}