//Making the refresh animation
const tl = gsap.timeline({ defaults: { ease: "power1.out" } });

tl.to(".text", { y: "0%", duration: 1, stagger: 0.25 });
tl.to(".slider", { y: "-100%", duration: 1.5, delay: 0.5 });
tl.to(".intro", { y: "-100%", duration: 1 }, "-=1");
//Wie schnell der text eingeflogen kommt
//tl.fromTo(".main", { opacity: 0 }, { opacity: 1, duration: 1 });
//tl.fromTo(".btn", { opacity: 0 }, { opacity: 1, duration: 1 }, "-=1");

//starting with acutal page
let wahrheiten = [
    "Wie viele Jungs / Mädchen hast du bisher geküsst?",
    "Bist du im Moment verliebt?",
    "Hast du schon mal mit einer Frau / einem Mann rumgemacht?",
    "Was war dein letzter Traum an den du dich erinnerst?",
    "Hast du schon mal etwas geklaut? Wenn ja, was?",
    "Was war dein schönstes Date?",
    "Was war dein schlimmstes Date?",
    "Wen in der Runde findest du am interessantesten?",
    "Mit wem in der Runde würdest du am liebsten einen Urlaub verbringen?",
    "Hast du schon mal eine Straftat begangen?",
    "Mit wem hattest du deinen ersten Kuss?",
    "Was würdest du machen, wenn du für einen Tag ein Mann oder eine Frau wärst?",
    "Welches Tier wärst du am liebsten?",
    "Hast du schon mal illegale Drogen genommen?",
    "Wen in der Runde findest du am attraktivsten?",
    "Wonach hast du als letztes gegoogelt?",
    "Wer in der Runde ist am besten angezogen und warum?",
    "Welches ist dein aktuelles Lieblingslied?",
    "Von wem hast du deinen letzten Korb bekommen?",
    "Hast du schon mal auf dem Klo telefoniert?",
    "Was war das gemeinste, was du je getan hast?",
    "Was war das kriminellste, was du je getan hast?",
    "Hast du schon mal sexy Bilder von der verschickt?",
    "Würdest du mit jemandem knutschen, den du gerade erst kennengelernt hast?",
    "Was findest du an dir am sexiesten?",
    "Wofür hast du dich in letzter Zeit geschämt?",
    "Worauf guckst du zuerst, wenn du jemanden kennenlernst?",
    "Wie kann man dich am schnellsten von sich begeistern?",
    "Was würdest du machen, wenn du für einen Tag unsichtbar wärst?",
    "Wer in der Runde hat die schönsten Lippen?",
    "Wer in der Runde hat den schönsten Hintern?",
    "Wie sieht dein Traumdate aus?",
    "Mit wem in der Runde würdest du gerne für einen Tag das Leben tauschen?",
    "Welche Körperstellen rasierst du regelmäßig?",
    "Was war deine letzte Lüge?",
    "Welches Abenteuer würdest du gerne noch erleben?",
    "Hast du schon mal jemanden betrogen?",
    "Was würdest du an deinem Körper verändern wenn du könntest?",
    "Was würdest du machen, wenn du nur noch eine Stunde zu leben hättest?",
    "Was turnt dich bei Frauen/Männern besonders an?",
    "Wenn du mit einer Person in der Runde schlafen müsstest, wen würdest du auswählen?",
    "Wen in der Runde würdest du am ehesten küssen und warum?",
    "Wie schafft man es am besten dich zu erregen?",
    "Wie kriegt man dich am besten rum?",
    "Bist du eher dominant oder devot?",
    "Welche Kleidung findest du besonders sexy an dir?",
    "Welches Pornogenre findest du am besten?",
    "Erzähle allen von einer Sexphantasie. ",
    "Schätze wer in der Runde am besten im Bett ist und warum. ",
    "In wen aus der Runde könntest du dich am ehesten verlieben?",
    "Was magst du nicht an dir?",
    "Was war die mutigste Aktion deines Lebens? ",
    "Wen in diesem Raum magst du am meisten?",
    "In welchen Star warst du früher unsterblich verknallt?",
    "Welche Charaktereigenschaften magst du an dir?",
    "Was hältst du für deine beste Eigenschaft? Und was ist die Schlechteste?",
    "Welcher Mitspieler hat die schönsten Hände?",
    "Auf eine Skala von 1 – 10: Für wie gut aussehend hältst du dich?",
    "Wenn du in die Runde schaust, wer wird später am meisten Geld verdienen?",
    "Was ist die interessanteste Narbe oder der interessanteste Fleck auf deinem Körper?",
    "Wieso ist die Person rechts von dir schön?",
    "Was ist das Peinlichste, das du je gemacht hast?",
    "Was hältst du für deine beste Eigenschaft? Und was ist die schlechteste?",
    "Verrate mir ein Geheimnis aus deiner Kindheit.",
    "Was ist dein größtes (geheimes) Laster?",
    "Was ist das Mutigste, das du je getan hast?",
    "Wen aus der Runde würdest du am liebsten in ein Schwein verzaubern?",
    "Wovon träumst du beim Schlafen am häufigsten?",
    "Wenn du illegal dein Geld verdienen würdest, womit würdest du es verdienen?",
    "Wenn du blind wärst, wer aus der Runde wäre dein Blindenhund?",
    "Womit kann man dich am meisten beeindrucken?",
    "Wenn du ab jetzt für den Rest des Abends nur noch 3 Worte benutzen dürftest um dich auszudrücken – welche wären es?",
    "Wenn du Diktator wärst, welches Gesetz würdest du als erstes erlassen?",
    "Wenn du zur Nazi-Zeit gelebt hättest, wer wärst du gewesen?",
    "Was war das peinlichste Erlebnis in deiner Schulzeit / Studienzeit / Ausbildung / im letzten Jahr?",
    "Was war der größte Fehler deines Lebens?",
    "Was würdest du niemals tun – auch wenn du weißt, du hast nur noch 12 h zu leben?",
    "Welche Straftat hast du schon begangen?",
    "Was würdest du gerne mal bei mir… (bei Person xy) machen, wenn du danach mein (ihr, sein…) Gedächtnis löschen könntest?",
    "Was ist das Schlimmste, was du je jemanden angetan hast?",
    "In wen warst du bis jetzt am heftigsten verknallt?",
    "Warst du schon einmal in einen der hier Anwesenden verliebt?",
    "Wenn du ein Vampir wärst, wen von uns würdest du jetzt beißen?",
    "Was ist das Schlimmste was du je erlebt hast?",
    "Was war dein schlimmster Korb?",
    "Was ist deine dunkelste Fantasie?",
    "Was ist das Schönste, dass du je mit einem anderen Menschen erlebt hast?",
    "Was ist für dich der größte Abturner, den es gibt?",
    "Was findest du an deinem Körper am schönsten und was am hässlichsten?",
    "Wen aus unserer Runde möchtest du am liebsten nackt sehen?",
    "In wen aus der Runde könntest du dich am ehesten verlieben?",
    "Hattest du schon mal einen erotischen Traum in dem jemand aus dieser Runde vorkam?",
    "Wenn du dich im Intimbereich tätowieren würdest – was stünde dort?",
    "Was ist wichtiger in einer Beziehung – Sex oder Liebe?",
    "Findest du Sex geil, gut, okay, ab und an ganz nett – oder ist er dir nicht so wichtig?",
    "Was macht für dich richtig guten Sex aus?",
    "Wie oft in der Woche / im Monat hast du Sex – und wie oft hättest du gerne Sex?",
    "Mit wie vielen unterschiedlichen Sexpartnern hast du schon geschlafen?",
    "Welches Körperteil turnt dich am meisten an?",
    "Wie, wo und mit wem hattest du dein erstes Mal?",
    "Wie wichtig ist ein ausgedehntes Vorspiel für dich?",
    "Was muss ein Mann / eine Frau tun, um dich zu verführen?",
    "Hattest du schon mal einen Dreier? Und wie fandest du es?",
    "Hattest du schon mal Sex mit einem guten Freund?",
    "Hattest du schon mal Sex mit einem aus dieser Runde – außer deinem Partner?",
    "Was ist der peinlichste Moment beim Sex, den du je hattest?",
    "Du bist total verliebt, aber dann zieht er/sie sich aus. Was müsste passieren, damit du schreiend davon läufst?",
    "Worauf achtest du bei einer Frau zuerst – Brüste, Hintern oder Gesicht?",
    "Worauf achtest du bei einem Mann zuerst und was muss er haben damit du denkst: awwwww, geil!",
    "Hast du dich schon mal beim Gedanken an einen aus dieser Runde befriedigt?",
    "Was ist deine Lieblingsstellung beim Sex?",
    "Was ist beim Sex für dich ein absolutes Tabu?",
    "Was ist das geilste, was du je getan hast?",
    "Hattest du schon mal Cybersex oder Telefonsex – und mit wem?",
    "Was ist dein versautester geheimer Wunsch?",
    "Was ist schöner – beschnitten oder unbeschnitten?",
    "Mit wem aus dieser Runde glaubst du, hättest du den besten Sex?",
    "Wem würdest du Geld dafür geben, mit dir zu schlafen?",
    "Was war dein verrücktestes Sex-Erlebnis?",
    "Hattest du schon mal gefährlichen Sex – und wie genau war das?",
    "Hattest du schon mal Sex mit einem Unbekannten? z.B. von Tinder?",
    "Woran denkst du am liebsten, wenn du dich selbst befriedigst?",
    "Hast du schon einmal Sex mit dem gleichen Geschlecht gehabt?",
    "Du hattest mit mir Sex. Was würdest du danach zu mir sagen?",
    "Wie kann man dich am besten flach legen?",
    "Mit wem würdest du auf jeden Fall schlafen – egal ob du verheiratet bist oder unsterblich verliebt?",
    "Mit wem hattest du den besten Sex deines Lebens?",
    "Hast du schon mal für Sex bezahlt?",
    "Über wen hattest du deinen letzten heißen Traum?",
    "Bist du schon mal beim Sex überrascht worden – und von wem?"
    ]
    
let titleEl = document.getElementById("title").innerHTML = get_random(wahrheiten)
let refreshBtn = document.getElementById("refresh-btn")

function get_random (list) {
    return list[Math.floor((Math.random()*list.length))];
}

refreshBtn.addEventListener('click', function(){
    window.location.reload()
})
