//Making the refresh animation
const tl = gsap.timeline({ defaults: { ease: "power1.out" } });

tl.to(".text", { y: "0%", duration: 1, stagger: 0.25 });
tl.to(".slider", { y: "-100%", duration: 1.5, delay: 0.5 });
tl.to(".intro", { y: "-100%", duration: 1 }, "-=1");
//Wie schnell der text eingeflogen kommt
//tl.fromTo(".main", { opacity: 0 }, { opacity: 1, duration: 1 });
//tl.fromTo(".btn", { opacity: 0 }, { opacity: 1, duration: 1 }, "-=1");

//starting with acutal page
let ihnn = [
    "einen Jungen/ein Mädchen geküsst",
    "Analsex gehabt",
    "einen Blowjob gegeben",
    "einen Blowjob bekommen",
    "einen Dreier gehabt",
    "einen Porno geschaut",
    "masturbiert",
    "einen One-Night-Stand gehabt",
    "einen Filmriss gehabt",
    "gestrippt",
    "ein von Sex mit einem Freund oder Freundin (oder nenne einen Freund/Freundin, von dem du es vermutest ;) ) phantasiert",
    "beim Sex gelacht",
    "nach dem Sex geweint",
    "meinen Intimbereich fotografiert",
    "Sex gehabt, den ich jetzt bereue",
    "ein Bild verschickt, das ich besser nicht verschickt hätte",
    "Viagra genommen",
    "meinem Expartner nachspioniert",
    "ein Sexspielzeug benutzt",
    "einen One Night Stand gehabt",
    "eine Person geküsst, die gerade mitspielt",
    "mit einer Person geschlafen, die gerade mitspielt",
    "davon geträumt eine Person zu küssen, die gerade mitspielt",
    "einer Person auf den Hintern gestarrt, die gerade mitspielt",
    "mit zwei Personen an einem Tag geschlafen",
    "Sex in der Öffentlichkeit gehabt",
    "Sex am Strand gehabt",
    "Sex in der Küche gehabt",
    "mehrere Orgasmen nacheinander gehabt",
    "einen Orgasmus vorgetäuscht",
    "eine Stellung aus dem Kamasutra ausprobiert",
    "nach dem Sex masturbiert",
    "um Sex gebettelt",
    "von Sex geträumt",
    "mehr als 3x an einem Tag masturbiert",
    "mit meinem Partner über meine Phantasien gesprochen",
    "meinem Partner im Bett Anweisungen gegeben",
    "ein Trinkspiel nackt gespielt",
    "mit einem Expartner geschlafen",
    "während dem Sex an eine andere Person gedacht",
    "Sperma geschluckt",
    "für Sex bezahlt",
    "Sex im Schwimmbad gehabt. ",
    "einen Porno geschaut.",
    "Sex gehabt, während eine andere Person im Raum war. ",
    " jemand beim Sex erwischt. ",
    "jemanden entjungfert",
    "Telefonsex gehabt. ",
    "eine Affäre mit einem vergebenen Mann gehabt. ",
    "etwas in einem Sex-Shop gekauft. ",
    "Sex im Flugzeug gehabt.",
    "Sexfantasien über einen guten Freund gehabt. ",
    "mehr als drei Orgasmen an einem Tag gehabt.",
    "in der Woche einmal täglich Sex gehabt.",
    "Liebeskugeln verwendet.",
    " Nacktfotos verschickt.",
    "meine Unterwäsche im Club vergessen",
    "ein Kondom mit Geschmack benutzt",
    "Sex im Schlafzimmer meiner Eltern gehabt",
    "Strippoker mit Freunden gespielt",
    "ein Kondom während dem Sex kaputt gemacht",
    "etwas bei Eis.de bestellt",
    "beim Sex lachen müssen",
    "beim Sex an jemand anderen gedacht",
    "Pornos online geschaut",
    "Oralsex gehabt",
    "Sex im Auto gehabt",
    "Sex in einer öffentlichen Toilette gehabt",
    "einen Orgasmus vorgespielt",
    "jemandem bei der Selbstbefriedigung zugeschaut",
    "während der Periode Sex gehabt",
    "Sex mit dem Ex gehabt",
    "einen Puff besucht",
    "nackt vorm PC gesessen",
    "meinen Intimbereich rasiert",
    "Analsex gehabt",
    "eine Geschlechtskrankheit gehabt",
    "jemanden mit Mundgeruch geküsst",
    "ungeduscht Sex gehabt",
    "im Intimbereich gestunken",
    "im Wald einen geblasen bekommen",
    "Obst oder Gemüse als Sextoy benutzt",
    "eine Schmutzige-Nachricht verschickt",
    "S*x mit jemandem, der 10 Jahre älter war als ich gehabt",
    "S*x mit jemandem, der 5 Jahre jünger war als ich gehabt",
    "mit jemandem an meinem Arbeitsplatz geschlafen",
    "beim S*x den falschen Namen gesagt",
    "über jemanden in diesem Raum fantasiert",
    "über jemanden in diesem Raum fantasiert",
    "mit einer Person geflirtet, um eine Wette zu gewinnen",
    "mehr als 10 S*xualpartner gehabt",
    "so getan, als würde ich jemanden lieben",
    "Orals*x an einem öffentlichen Ort gegeben oder bekommen",
    " schmutzige Rollenspiele versucht",
    "während dieses Spiels gelogen",
    "jemand geleckt",
    "Nacktfotos von mir / jemandem gemacht",
    "einen Korb bekommen",
    "meinen Partner beim S*x geschlagen",
    "mit jemandem geschlafen, von dem ich dachte, er sei hässlich"
    ]
let textEl1 = document.getElementById("text1").innerHTML = get_random(ihnn)

function get_random (list) {
    return list[Math.floor((Math.random()*list.length))];
}